name: Build and push Docker images

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  docker:
    name: Build and push Docker images
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get variables
        id: variables
        run: |
          major_minor_patch=$(grep -oP '^FROM\s+\S+:\K[0-9]+\.[0-9]+\.[0-9]+' Dockerfile)
          major_minor=$(grep -oP '^FROM\s+\S+:\K[0-9]+\.[0-9]+' Dockerfile)
          major=$(grep -oP '^FROM\s+\S+:\K[0-9]+' Dockerfile)
          echo "major_minor_patch=${major_minor_patch}" >> $GITHUB_OUTPUT
          echo "major_minor=${major_minor}" >> $GITHUB_OUTPUT
          echo "major=${major}" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_DOCKERHUB_PASSWORD }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,amd64

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Push to DockerHub
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: |
            opengovsg/nginx-open-dev-ports:latest
            opengovsg/nginx-open-dev-ports:${{ steps.variables.outputs.major_minor_patch }}
            opengovsg/nginx-open-dev-ports:${{ steps.variables.outputs.major_minor }}
            opengovsg/nginx-open-dev-ports:${{ steps.variables.outputs.major }}
          platforms: linux/arm64,linux/amd64
          push: true
          provenance: true
          sbom: true
